### ISSUE TITLE
Add MIT Licence inside Nuget

### ISSUE THREAD

**Issue by viniciuscluna** [webmotions/fake-authentication-jwtbearer#11]
Hi all, I see that this component does not have any license inside Nuget. 
https://www.nuget.org/packages/WebMotions.Fake.Authentication.JwtBearer/
Is it possible to add? 
Thank you :)

**Comment by DOMZE** [comment]
Hello,

Yes I will once I have some changes to do.

**Comment by DOMZE** [comment]
Fixed in 6.1.0
