### ISSUE TITLE
Why is necessary a launchSettings.json in the project?

### ISSUE THREAD

**Issue by pedrofernandesfilho** [webmotions/fake-authentication-jwtbearer#2]
When I install this package on my integration test project, a directory `Properties` with a `launchSettings.json` file is created.

How its works? Why this file is needed?

If I remove this `launchSettings.json`, a line is included on `.csproj`.

```
  <ItemGroup>
    <Content Remove="...\...\.nuget\packages\webmotions.fake.authentication.jwtbearer\3.1.0\contentFiles\any\netcoreapp3.1\Properties\launchSettings.json" />
  </ItemGroup>
```

**Comment by DOMZE** [comment]
Hello,

The file is from the initial fork and was not deleted. It can be safely deleted. I will clean it up once I find the time. It does not impact the project.
