### ISSUE TITLE
Adding multiple policies causes 403 responses

### ISSUE THREAD

**Issue by Ronnehag** [webmotions/fake-authentication-jwtbearer#23]
I have a web API and a test project where I'm testing all endpoints, mocking authorized calls with this package.

In my test project I do the following:
```
builder.ConfigureTestServices(services =>
{
	services.AddAuthentication(FakeJwtBearerDefaults.AuthenticationScheme).AddFakeJwtBearer();
});
```

In my web api I have a policy configured:
```
services.AddAuthorizationBuilder()
	.AddPolicy("SamplePolicy", p =>
	{
              p.AddRequirements(new CustomRole(new List<string> { "Admin", "Editor"  }));
              p.RequireAuthenticatedUser();
	})
```

Test code:
```
var client = ApiFactory.CreateClient();
client.SetFakeBearerToken(TestingConstants.AuthorizedUserClaims);

public static readonly Dictionary<string, object> AuthorizedUserClaims = new()
{
  { "sub", "123" },
  { "email", "test@sample.com" },
  { "client_id", "sample" },
};

```

This has worked great and all tests passes.

Now I have a need to add another policy for one of the endpoints.
This policy will require a specific scope, added like this:
```
services.AddAuthorizationBuilder()
	.AddPolicy("SamplePolicy", p =>
	{
              p.AddRequirements(new CustomRole(new List<string> { "Admin", "Editor"  }));
              p.RequireAuthenticatedUser();
	})
        .AddPolicy("SecondPolicy", p =>
        {
            p.RequireAuthenticatedUser();
            p.AddRequirements(new ClaimsAuthorizationRequirement("scope", new[] { "some-master-scope" }));
        });

// Then it's added on a single endpoint like this
[Authorize(Policy = "SecondPolicy")]
```

When I add this policy all previous tests that uses the other Authorize attribute fails with a 403.
They work again when I add the claim "scope" with the value of "some-master-scope" to the token set by the SetFakeBearerToken method. I don't want to do this because this claim shouldn't be required by the other endpoints.
It's strange because there's only one method in one controller that has this Policy attribute, meaning this policy shouldn't run for any other call.

Why am I getting 403s here? Am I missing something obvious?

**Comment by DOMZE** [comment]
I'd suggest increasing your logs verbosity to Trace for the authorization namespace so that you can see all the actions that is happening.

This can give you insight as to what causes the other authorize to fail.

**Comment by Ronnehag** [comment]
I can see that it runs that policy by debugging, which is very strange since the endpoint I'm testing doesn't have that policy.
In that case it's most likely not an issue with this nuget, but instead something happening when running integration tests using the WebApplicationFactory.
